DROP TABLE IF EXISTS APP_CLUSTER_CONFIG_FILE;
CREATE TABLE APP_CLUSTER_CONFIG_FILE(
    ID VARCHAR(250) NOT NULL UNIQUE,
    CONFIG_FILE_NAME VARCHAR(250) UNIQUE,
    CONFIG_FILE_STATUS VARCHAR(50),
    CONFIG_FILE_BLOB BYTEA,
    CONFIG_FILE_DESCRIPTION VARCHAR(250)
);