#
# COPYRIGHT Ericsson 2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eric-vnfm-orchestrator-service.name" . }}-config
  labels: {{- include "eric-vnfm-orchestrator-service.labels.extended-defaults" . | nindent 4 }}
  annotations: {{- include "eric-vnfm-orchestrator-service.annotations" . | nindent 4 }}
data:
  application.yml: |-
    vnfm:
      host: {{ .Values.global.hosts.vnfm | quote }}
    notifications:
      enabled: {{ .Values.notifications.enabled }}
    redis:
      acl:
        enabled: {{ .Values.redis.acl.enabled }}
    spring:
      redis:
        host: {{ .Values.redis.host }}
        port: {{ include "eric-vnfm-orchestrator-service.redis.port" . }}
    lcmOperationConfig:
      lcmOperationsLimit: {{ .Values.lcmOperationConfig.lcmOperationsLimit }}
    entityConverter:
      cache:
        enabled: {{ .Values.crypto.cache.enabled }}