#
# COPYRIGHT Ericsson 2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

spring:
  datasource:
    url: ${DB_URL}
    port: 34062 # Default port to access postgres
    hikari:
      data-source-properties: stringtype=unspecified
  flyway.locations: classpath:db/migration,classpath:db/dev
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

stubrunner:
  work-offline: true
  ids:
    - com.ericsson.orchestration.mgmt:eric-am-common-wfs-server:::10103
    - com.ericsson.orchestration.mgmt.packaging:eric-am-onboarding-server:::10102

management:
  endpoints:
    web:
      exposure:
        include: "*"

# Overriding of default output format (json) by empty config file to log in plain format (log lines).
logging:
  config: ''
  level:
    org.springframework.amqp.rabbit: OFF
