#
# COPYRIGHT Ericsson 2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orchestrator  # Prerequisite:: have the port forwarding to postgres in the cluster in place
    username: postgres
    password: postgres
    hikari:
      data-source-properties: stringtype=unspecified
  flyway.locations: classpath:db/migration
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            # Included to hide exception which does not fail startup. More info: https://hibernate.atlassian.net/browse/HHH-12368
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
      temp:
      use_jdbc_metadata_defaults: false
      dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9002

workflow:
  host: localhost:9003    # With this you can either port forward to the WFS in the cluster or run WFS in a separate intellij session

onboarding:
  host: http://localhost:9001 # With this you can either port forward to the onboarding in the cluster or run onboarding in a separate intellij session
  path: "/api/vnfpkgm/v1/vnf_packages"
  queryValue: "(eq,vnfdId,%s)"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    rabbit:
      enabled: false

# Overriding of default output format (json) by empty config file to log in plain format (log lines).
logging:
  config: ''
  level:
    org.springframework.amqp.rabbit: OFF
