{{- $acldata := "" }}
{{- if (.Values.security.acl.enabled) }}
  {{- $users := default list .Values.security.acl.users }}
  {{- if not (eq (include "eric-cloud-native-kvdb-rd-operand.isDefaultUserInUsersList" $users) "true") }}
    {{- $defaultuser := dict "name" "default" "permissions" "~* &* +@all -@dangerous +client +cluster +config|get +info +latency +slowlog +monitor +keys +flushdb" }}
    {{- $users = prepend $users $defaultuser }}
  {{- end }}
  {{- range $user := $users }}
    {{- include "eric-cloud-native-kvdb-rd-operand.validateUser" $user }}
    {{- $secretName := printf "%s-%s-%s" (include "eric-cloud-native-kvdb-rd-operand.name" $) "secret" $user.name -}}
    {{- $secret := lookup "v1" "Secret" $.Release.Namespace $secretName -}}
    {{- $userpass := "" }}
    {{- if $secret }}
      {{- $userpass = $secret.data.password | b64dec }}
    {{- else }}
      {{- $userpass = include "eric-cloud-native-kvdb-rd-operand.passwordGenerator" . }}
    {{- end }}
    {{- $hashedUserpass := $userpass | sha256sum }}
  {{- $acldata = printf "user %s on #%s %s\n%s" $user.name $hashedUserpass $user.permissions $acldata }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "eric-cloud-native-kvdb-rd-operand.labels" $ | nindent 4 }}
  annotations:
    {{- include "eric-cloud-native-kvdb-rd-operand.annotations" $ | nindent 4 }}
type: kubernetes-io/basic-auth
stringData:
  username: {{ $user.name }}
  password: {{ $userpass }}

---
  {{- end }}
{{- end }}

{{- if (.Values.security.acl.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eric-cloud-native-kvdb-rd-operand.name" . }}-users-acl
  labels:
    {{- include "eric-cloud-native-kvdb-rd-operand.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-cloud-native-kvdb-rd-operand.annotations" . | nindent 4 }}
type: Opaque
stringData:
  users.acl: |
    {{- $acldata | nindent 4 }}
{{- end }}
