{{- $g := fromJson (include "eric-cloud-native-kvdb-rd-operand.global" .) -}}
{{- if ($g.security.tls.enabled) }}
apiVersion: siptls.sec.ericsson.com/v1
kind: InternalCertificate
metadata:
  name: {{ template "eric-cloud-native-kvdb-rd-operand.name" . }}-client-certificate
  labels:
    {{- include "eric-cloud-native-kvdb-rd-operand.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-cloud-native-kvdb-rd-operand.annotations" . | nindent 4 }}
spec:
  kubernetes:
    generatedSecretName: {{ template "eric-cloud-native-kvdb-rd-operand.clientSecretName" . }}
    certificateName: cert.pem
    privateKeyName: privkey.pem
  certificate:
    subject:
      cn: {{ template "eric-cloud-native-kvdb-rd-operand.name" . }}
    {{- if .Values.security.tls.certificateTTL }}
    validity:
      overrideTtl: {{ .Values.security.tls.certificateTTL }}
    {{- end }}
    extendedKeyUsage:
      tlsClientAuth: true
      tlsServerAuth: false
    issuer:
      reference: {{ template "eric-cloud-native-kvdb-rd-operand.name" . }}-client-ca
{{- end }}
