apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "eric-cloud-native-kvdb-rd-operand.name" . }}
  labels:
    {{- include "eric-cloud-native-kvdb-rd-operand.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-cloud-native-kvdb-rd-operand.annotations" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - namespaces
      - services
      - endpoints
      - pods
    verbs: ["list", "get"]
  - apiGroups: ["kvdbrd.gs.ericsson.com"]
    resources:
      - redisclusters
    verbs: ["list", "get"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "eric-cloud-native-kvdb-rd-operand.name" . }}
  labels:
    {{- include "eric-cloud-native-kvdb-rd-operand.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-cloud-native-kvdb-rd-operand.annotations" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "eric-cloud-native-kvdb-rd-operand.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "eric-cloud-native-kvdb-rd-operand.name" . }}
    namespace: {{ .Release.Namespace }}
