apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eric-cloud-native-kvdb-rd-operand.name" . }}
  labels:
    {{- include "eric-cloud-native-kvdb-rd-operand.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-cloud-native-kvdb-rd-operand.annotations" . | nindent 4 }}
automountServiceAccountToken: true
