#
# COPYRIGHT Ericsson 2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "eric-vnfm-orchestrator-service.name" . }}-role-binding
  labels: {{- include "eric-vnfm-orchestrator-service.labels.extended-defaults" . | nindent 4 }}
  annotations: {{- include "eric-vnfm-orchestrator-service.annotations" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name:  {{ template "eric-vnfm-orchestrator-service.name" . }}-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ template "eric-vnfm-orchestrator-service.serviceAccount.name" . }}