---------------------- Add temp instance for multi charts -----------------------
UPDATE APP_VNF_INSTANCE
SET temp_instance = '{"vnfInstanceId":"rf1ce-4cf4-477c-aab3-21c454e6a379","vnfInstanceName":"messaging-charts","vnfInstanceDescription":"",' ||
                    '"vnfDescriptorId":"d3def1ce-4cf4-477c-aab3-21cb04e6a379","vnfProviderName":"Ericsson","vnfProductName":"SGSN-MME",' ||
                    '"vnfSoftwareVersion":"1.20(CXS101289_R81E08)","vnfdVersion":"cxp9025898_4r81e08","vnfPackageId":"9308748274545350044",' ||
                    '"instantiationState":"INSTANTIATED","clusterName":"default","namespace":"crd-single-cnf",' ||
                    '"helmCharts":[{"id":"r1f1ce-4cf4-477c-aab3-21c454e6a379","helmChartUrl":"https://arm.epk.ericsson.se/artifactory/proj-am-helm-local/acceptance-test/spider-app-2.74.7.tgz","priority":1,"releaseName":"messaging-charts-1","state":"COMPLETED","helmChartName":"spider-app","helmChartVersion":"2.74.7","helmChartType":"CNF"},
                    {"id":"r2f1ce-4cf4-477c-aab3-21c454e6a379","helmChartUrl":"https://arm.epk.ericsson.se/artifactory/proj-am-helm-local/acceptance-test/spider-app-2.74.8.tgz","priority":2,"releaseName":"messaging-charts-2","state":"COMPLETED","helmChartName":"spider-app","helmChartVersion":"2.74.8","helmChartType":"CNF"}],' ||
                    '"operationOccurrenceId":"rm8fcbc8-474f-4673-91ee-761fd83991e6","allOperation":[{"operationOccurrenceId":"rm8fcbc8-474f-4673-91ee-761fd83991e6",' ||
                    '"operationState":"COMPLETED","grantId":null,"lifecycleOperationType":"INSTANTIATE","automaticInvocation":false,' ||
                    '"operationParams":"{\"flavourId\":null,\"instantiationLevelId\":null,\"clusterName\":null,\"extVirtualLinks\":null,\"extManagedVirtualLinks\":null,' ||
                    '\"localizationLanguage\":null,\"additionalParams\":{\"namespace\":\"cnf-with-crd-ns\"}}","cancelPending":false,"error":null,"valuesFileParams":null,' ||
                    '"vnfSoftwareVersion":"1.20(CXS101289_R81E08)","vnfProductName":"SGSN-MME","cancelModeType":null},' ||
                    '{"operationOccurrenceId":"334a3ce0-ec57-44c5-a397-8ab34e3f367a","operationState":"STARTING","grantId":null,"lifecycleOperationType":' ||
                    '"CHANGE_PACKAGE_INFO","automaticInvocation":false,"operationParams":"{\"vnfdId\":\"3d02c5c9-7a9b-48da-8ceb-46fcc83f584c\",\"additionalParams\":{}}",' ||
                    '"cancelPending":false,"error":null,"valuesFileParams":null,"vnfSoftwareVersion":"1.20(CXS101289_R81E08)",' ||
                    '"vnfProductName":"SGSN-MME","cancelModeType":null}],"ossTopology":"{\"disableLdapUser\":{\"type\":\"boolean\",\"required\":\"false\"}}",' ||
                    '"instantiateOssTopology":"{\"disableLdapUser\":{\"type\":\"boolean\",\"required\":\"false\"}}","addNodeOssTopology":null,"addedToOss":false,' ||
                    '"combinedValuesFile":null,"combinedAdditionalParams":"{\"eric-pc-up-data-plane.networkInstances[3].link.ipv6\": \"2a01:04c8:f401:0010::ff/64\",\"eric-pc-up-data-plane.networkInstances[3].link.ipv4\": \"10.251.0.101/28\",\"eric-pc-up-data-plane.networkInstances[2].interfaces[0]\": \"if-cp\",\"eric-pc-up-data-plane.applications[18].name\": \"ff_ee_freeratedsrv_sightcall\",\"eric-pc-up-data-plane.networkInstances[2].name\": \"SxN4\",\"eric-pc-up-data-plane.applications[10].name\": \"ff_ee_portal_url\",\"eric-cnom-server.service.loadBalancerIP\": \"10.128.28.83\",\"eric-pc-up-pfcp-endpoint.networkInstances[0].link.ipv4\": \"10.251.0.53/28\",\"eric-pc-up-data-plane.interfaces[2].ipv4\": \"193.36.80.4\",\"eric-pc-up-data-plane.interfaces[3].name\": \"if-access-s5u-n9\",\"eric-pc-up-data-plane.applications[23].name\": \"ff_generic_nhs_https\",\"eric-pc-up-data-plane.applications[8].name\": \"ff_ee_portal_ip_lab\",\"eric-pc-up-data-plane.applications[17].name\": \"ff_ee_freeratedsrv_qisda\",\"eric-fh-snmp-alarm-provider.service.annotations.metallb\\\\.universe\\\\.tf\\\\/allow-shared-ip\": \"fm-pm\",\"eric-pc-up-data-plane.applications[11].name\": \"ff_ee_portal_url_lab\",\"eric-pc-up-data-plane.networkInstances[3].name\": \"SGiN6\",\"eric-pc-up-data-plane.applications[1].name\": \"ff_ee_dns\",\"eric-pc-up-data-plane.networkInstances[2].link.ipv4\": \"10.251.0.53/28\",\"eric-pc-up-data-plane.applications[16].name\": \"ff_ee_freeratedsrv_ota\",\"eric-pc-up-data-plane.networkInstances[0].vlan\": \"1009\",\"eric-pc-up-data-plane.interfaces[2].type\": \"core\",\"eric-pc-up-data-plane.interfaces[4].name\": \"if-core-sgi-n6\",\"eric-pc-up-data-plane.networkInstances[0].gateway.ipv4\": \"10.251.0.65\",\"eric-pm-bulk-reporter.service.annotations.\\\"metallb\\\\.universe\\\\.tf\\\\/allow-shared-ip\\\"\": \"fm-pm\",\"eric-pc-up-data-plane.interfaces[1].name\": \"if-access-slu-n3\"}","policies":null,"resourceDetails":"",' ||
                    '"scaleInfoEntity":[],"manoControlledScaling":null}'
WHERE vnf_id = 'rf1ce-4cf4-477c-aab3-21c454e6a379';





UPDATE APP_VNF_INSTANCE
SET temp_instance = '{"vnfInstanceId":"rf1ce-4cf4-477c-aab3-21c454e6a379200","vnfInstanceName":"messaging-charts-22","vnfInstanceDescription":"",' ||
                    '"vnfDescriptorId":"d3def1ce-4cf4-477c-aab3-21cb04e6a379","vnfProviderName":"Ericsson","vnfProductName":"SGSN-MME",' ||
                    '"vnfSoftwareVersion":"1.20(CXS101289_R81E08)","vnfdVersion":"cxp9025898_4r81e08","vnfPackageId":"9308748274545350044",' ||
                    '"instantiationState":"INSTANTIATED","clusterName":"default","namespace":"crd-single-cnf",' ||
                    '"helmCharts":[{"id":"r1f1ce-4cf4-477c-aab3-21c454e6a379200","helmChartUrl":"https://arm.epk.ericsson.se/artifactory/proj-am-helm-local/acceptance-test/spider-app-2.74.7.tgz","priority":1,"releaseName":"messaging-charts-22-1","state":"COMPLETED","helmChartName":"spider-app","helmChartVersion":"2.74.7","helmChartType":"CNF"},
                    {"id":"r2f1ce-4cf4-477c-aab3-21c454e6a379200","helmChartUrl":"https://arm.epk.ericsson.se/artifactory/proj-am-helm-local/acceptance-test/spider-app-2.74.8.tgz","priority":2,"releaseName":"messaging-charts-22-2","state":"COMPLETED","helmChartName":"spider-app","helmChartVersion":"2.74.8","helmChartType":"CNF"}],' ||
                    '"operationOccurrenceId":"rm8fcbc8-474f-4673-91ee-761fd83991e6200","allOperation":[{"operationOccurrenceId":"rm8fcbc8-474f-4673-91ee-761fd83991e6",' ||
                    '"operationState":"COMPLETED","grantId":null,"lifecycleOperationType":"INSTANTIATE","automaticInvocation":false,' ||
                    '"operationParams":"{\"flavourId\":null,\"instantiationLevelId\":null,\"clusterName\":null,\"extVirtualLinks\":null,\"extManagedVirtualLinks\":null,' ||
                    '\"localizationLanguage\":null,\"additionalParams\":{\"namespace\":\"cnf-with-crd-ns\"}}","cancelPending":false,"error":null,"valuesFileParams":null,' ||
                    '"vnfSoftwareVersion":"1.20(CXS101289_R81E08)","vnfProductName":"SGSN-MME","cancelModeType":null},' ||
                    '{"operationOccurrenceId":"334a3ce0-ec57-44c5-a397-8ab34e3f367a","operationState":"STARTING","grantId":null,"lifecycleOperationType":' ||
                    '"CHANGE_PACKAGE_INFO","automaticInvocation":false,"operationParams":"{\"vnfdId\":\"3d02c5c9-7a9b-48da-8ceb-46fcc83f584c\",\"additionalParams\":{}}",' ||
                    '"cancelPending":false,"error":null,"valuesFileParams":null,"vnfSoftwareVersion":"1.20(CXS101289_R81E08)",' ||
                    '"vnfProductName":"SGSN-MME","cancelModeType":null}],"ossTopology":"{\"disableLdapUser\":{\"type\":\"boolean\",\"required\":\"false\"}}",' ||
                    '"instantiateOssTopology":"{\"disableLdapUser\":{\"type\":\"boolean\",\"required\":\"false\"}}","addNodeOssTopology":null,"addedToOss":false,' ||
                    '"combinedValuesFile":null,"combinedAdditionalParams":"{\"eric-pc-up-data-plane.networkInstances[3].link.ipv6\": \"2a01:04c8:f401:0010::ff/64\",\"eric-pc-up-data-plane.networkInstances[3].link.ipv4\": \"10.251.0.101/28\",\"eric-pc-up-data-plane.networkInstances[2].interfaces[0]\": \"if-cp\",\"eric-pc-up-data-plane.applications[18].name\": \"ff_ee_freeratedsrv_sightcall\",\"eric-pc-up-data-plane.networkInstances[2].name\": \"SxN4\",\"eric-pc-up-data-plane.applications[10].name\": \"ff_ee_portal_url\",\"eric-cnom-server.service.loadBalancerIP\": \"10.128.28.83\",\"eric-pc-up-pfcp-endpoint.networkInstances[0].link.ipv4\": \"10.251.0.53/28\",\"eric-pc-up-data-plane.interfaces[2].ipv4\": \"193.36.80.4\",\"eric-pc-up-data-plane.interfaces[3].name\": \"if-access-s5u-n9\",\"eric-pc-up-data-plane.applications[23].name\": \"ff_generic_nhs_https\",\"eric-pc-up-data-plane.applications[8].name\": \"ff_ee_portal_ip_lab\",\"eric-pc-up-data-plane.applications[17].name\": \"ff_ee_freeratedsrv_qisda\",\"eric-fh-snmp-alarm-provider.service.annotations.metallb\\\\.universe\\\\.tf\\\\/allow-shared-ip\": \"fm-pm\",\"eric-pc-up-data-plane.applications[11].name\": \"ff_ee_portal_url_lab\",\"eric-pc-up-data-plane.networkInstances[3].name\": \"SGiN6\",\"eric-pc-up-data-plane.applications[1].name\": \"ff_ee_dns\",\"eric-pc-up-data-plane.networkInstances[2].link.ipv4\": \"10.251.0.53/28\",\"eric-pc-up-data-plane.applications[16].name\": \"ff_ee_freeratedsrv_ota\",\"eric-pc-up-data-plane.networkInstances[0].vlan\": \"1009\",\"eric-pc-up-data-plane.interfaces[2].type\": \"core\",\"eric-pc-up-data-plane.interfaces[4].name\": \"if-core-sgi-n6\",\"eric-pc-up-data-plane.networkInstances[0].gateway.ipv4\": \"10.251.0.65\",\"eric-pm-bulk-reporter.service.annotations.\\\"metallb\\\\.universe\\\\.tf\\\\/allow-shared-ip\\\"\": \"fm-pm\",\"eric-pc-up-data-plane.interfaces[1].name\": \"if-access-slu-n3\"}","policies":null,"resourceDetails":"",' ||
                    '"scaleInfoEntity":[],"manoControlledScaling":null}'
WHERE vnf_id = 'rf1ce-4cf4-477c-aab3-21c454e6a379200';