#
# COPYRIGHT Ericsson 2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

openapi: 3.0.3
info:
  version: 1.0.0
  title: EVNFM Configuration Interface
  description: >
    API used by E-VNFM to get its configurations information

servers:
  - url: '{protocol}://{hostname}/{basePath}'
    variables:
      protocol:
        default: https
      hostname:
        default: ${INGRESS_HOST_ADDRESS}
      basePath:
        default: vnfm/container/info/v1/

tags:
  - name: Configurations

paths:
  '/configurations':
    get:
      tags:
        - Configurations
      summary: Get EVNFM configuration information.
      description: >
        Use this GET method to get EVNFM configuration information. This request returns the availability of some services and the system version.
        
        > **Following the grace period, this API will be removed from the documentation and transition into an internal EVNFM API.
        If you have any concerns, please reach out to the EVNFM design team.**
      operationId: configurationsGet
      responses:
        '200':
          description: >
            200 OK
            On success, the content of the values is returned. The payload body
            shall contain information about the configuration state of the application and available services
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EvnfmProductConfiguration'
          headers:
            Content-Type:
              description: The MIME type of the body of the response.
              schema:
                type: string
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  responses:
    InternalServerError:
      description: |
        INTERNAL SERVER ERROR - If there is an application error not related to the client’s input that
        cannot be easily mapped to any other HTTP response code (a catch-all error), the API producer responds with this response code.
        The ProblemDetails structure is provided, and includes in the detail attribute more information about the source of the problem.
      headers:
        Content-Type:
          description: The MIME type of the body of the response.
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
  schemas:
    ProblemDetails:
      description: >
        The "status" and "detail" attributes are mandated to be included by the present
        document, to ensure that the response contains additional textual
        information about an error. It is possible that
        particular APIs in the present document, or particular
        implementations, define extensions to define additional attributes
        that provide more information about the error. The description
        column only provides some explanation of the meaning to Facilitate
        understanding of the design.
      type: object
      required:
        - status
        - detail
      properties:
        type:
          description: >
            A URI reference that identifies the problem type.
            It is encouraged that the URI provides human-readable documentation
            for the problem (e.g. using HTML) when de-referenced. 
            When this member is not present, its value is assumed to be "about:blank".
          type: string
          format: URI
        title:
          description: >
            A short, human-readable summary of the problem type. It should
            not change from occurrence to occurrence of the problem,
            except for purposes of localization. If type is given and
            other than "about:blank", this attribute shall also be
            provided. A short, human-readable summary of the problem
            type.
          type: string
        status:
          description: >
            The HTTP status code for this occurrence of the problem. The
            HTTP status code generated by the origin server for this 
            occurrence of the problem.
          type: integer
        detail:
          description: >
            A human-readable explanation specific to this occurrence of
            the problem.
          type: string
        instance:
          description: >
            A URI reference that identifies the specific occurrence of the
            problem. It may yield further information if de-referenced.
          type: string
          format: URI
    ProductDependency:
      description: >
        The object that contains the application dependent services that are available for this version.
      properties:
        name:
          description: >
            Describes the name of service
          type: string
        version:
          description: >
            Describes version of the service
          type: string
    EvnfmProductConfiguration:
      description: >
        The configuration used to state for example version of other options that would be needed by UI
      type: object
      required:
        - availability
      properties:
        name:
          description: >
            Describes the name of the application
          type: string
        version:
          description: >
            Describes version of the application
          type: string
        dependencies:
          description: >
            Describes a list of micro services that make up the application.
            This is only the services that have been defined by the EVNFM configuration internally.
          type: array
          items:
            $ref: '#/components/schemas/ProductDependency'
        availability:
          description: >
            Contains the key-value pair of services that are available. 
            For example, {"packages": true}
          type: object
