#
# COPYRIGHT Ericsson 2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

# Default values for eric-am-common-wfs-ui-dev-backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  security:
    tls:
      enabled: false
  ericsson:
    licensing:
      licenseDomains:
        - productType: "Ericsson_Orchestrator"
          swltId: "STB-EVNFM-1"
          customerId: 800141
          applicationId: "800141_STB-EVNFM-1_Ericsson_Orchestrator"
  licensing:
    sites:
      - hostname: "nelsaas-vnf2-thrift.sero.gic.ericsson.se"
        ip: "10.155.142.69"
        priority: 0

eric-eo-lm-consumer:
  database:
    service: eric-data-document-database-pg
    secret: eric-data-document-database-pg-secret

eric-lm-combined-server:
  enabled: true
  labels:
    eric-si-application-sys-info-handler-access: "true"
  database:
    credentials:
      secretName: eric-data-document-database-pg-secret
  licenseServerClient:
    asih:
      host: "eric-si-application-sys-info-handler"
      port: 8080

eric-data-document-database-pg:
  db:
    super-user: postgres
    super-pwd: postgres
    metrics-user: exporter
    metrics-pwd: postgres
    replica-user: replica
    replica-pwd: postgres
  credentials:
    kubernetesSecretName: eric-data-document-database-pg-secret
  persistentVolumeClaim:
    size: 4Gi
  postgresDatabase: licensemanager_db
  highAvailability:
    replicaCount: 3

eric-si-application-sys-info-handler:
  enabled: true
  asih:
    applicationId: cncs
    uploadSwimInformation: false
  applicationInfoService:
    hostname: "nelsaas-vnf2-thrift.sero.gic.ericsson.se"
    port: 9095
