#
# COPYRIGHT Ericsson 2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

# Had to rename this file to 'dockerfile' because BOB can't handle more than one 'Docker' file in the same repo
ARG BASE_IMAGE_VERSION
FROM armdocker.rnd.ericsson.se/proj-am/sles/sles-openjdk11:${BASE_IMAGE_VERSION}

COPY target/eric-vnfm-orchestrator-service-testware.jar /acc_tests/
COPY docker/entryPoint.sh /acc_tests/entryPoint.sh
RUN chmod +x /acc_tests/*.sh

ENTRYPOINT ["/acc_tests/entryPoint.sh"]
